cubes:
  - name: products
    data_source: default
    sql_table: public.products

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true
        public: true

      - name: name
        sql: name
        type: string

      - name: size
        sql: size
        type: string

    measures:
      - name: count
        type: count
        title: '# of products'

      - name: price
        type: sum
        title: Total USD
        sql: price_usd
        meta: 
          pretext: '$'
          posttext: ''
              # Measure for testing negative values
              
      - name: negative_values
        sql: (-1 * (RANDOM() * 100)) + 50
        type: number
        title: 'Negative Value'

      # Measure for testing decimal values
      - name: decimal_values
        sql: (RANDOM() * 5)
        type: number
        title: 'Decimal Value'
      
      # Measure for testing whole numbers less than 5
      - name: small_numbers
        sql: FLOOR(RANDOM() * 5)
        type: number
        title: 'Whole Numbers < 5'

    joins:
      - name: orders # the name of the data model to join to (not the table)
        sql: "{CUBE}.id = {orders}.product_id"
        relationship: one_to_many

    pre_aggregations:
    # Pre-aggregation definitions go here.
    # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started
