name: Verify Build for Vanilla Components

on:
  push:
    branches:
      - main

jobs:
  verify-build:
    name: Verify Build for Vanilla Components
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node_version: [18, 19, 20]

    steps:
      - name: Verify build on ${{ matrix.os }} and Node.js ${{ matrix.node_version }}
        run: echo "Verifying build on ${{ matrix.os }} and Node.js ${{ matrix.node_version }}"

      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm i

      - name: Build embeddable
        run: npm run embeddable:build

      - name: Send Slack notification on failure
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        with:
          status: ${{ job.status }}
          notification_title: "Vanilla Components Build Failed for ${{ matrix.os }} and Node.js ${{ matrix.node_version }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
