name: Verify Build for Vanilla Components

on:
  push:
    branches:
      - main

jobs:
  verify-build:
    name: Verify Build for Vanilla Components
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Verify build on ${{ matrix.os }}
        run: echo "Verifying build on ${{ matrix.os }}"

      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm i

      - name: Build embeddable
        run: npm run embeddable:build

      - name: Check for errors
        run: |
          if [ $? -ne 0 ]; then
            echo "Error found during build process"
            exit 1
          fi