name: Verify Build for Vanilla Components

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  verify-build:
    name: Verify Build for Vanilla Components
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node_version: [18, 19, 20]

    steps:
      - name: Verify build on ${{ matrix.os }} and Node.js ${{ matrix.node_version }}
        run: echo "Verifying build on ${{ matrix.os }} and Node.js ${{ matrix.node_version }}"

      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm i

      - name: Build embeddable
        run: npm run embeddable:build

      - name: Send Slack notification on failure
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: "Vanilla Components build {status_message} for ${{ matrix.os }} and Node.js ${{ matrix.node_version }}"
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
          footer: 'Linked to Repo <{repo_url}|{repo}>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
